name: TestDoc
markdown: kramdown
kramdown:
   input: GFM
   
permalink: /blogs/:year/:month/:day/:title

# Where things are
source:       .
destination:  ./_site
plugins_dir:  ./_plugins
layouts_dir:  ./_layouts
data_dir:     ./_data
includes_dir: ./_includes
collections:  null
